AEA-6370 Add token exchange to PR workflow.

diff --git a/.github/workflows/pull_request.yaml b/.github/workflows/pull_request.yaml
--- a/.github/workflows/pull_request.yaml
+++ b/.github/workflows/pull_request.yaml
@@ -57,3 +57,42 @@ jobs:
     secrets:
       AUTOMERGE_APP_ID: ${{ secrets.AUTOMERGE_APP_ID }}
       AUTOMERGE_PEM: ${{ secrets.AUTOMERGE_PEM }}
+
+  token:
+    name: Retrieve PyPI Token
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Retrieve PyPI OIDC token
+        id: retrieve-pypi-oidc-token
+        run: |
+          set -euo pipefail
+
+          resp=$(curl -sSf -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
+                  "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=pypi")
+
+          if ! oidc_token=$(jq -er '.value' <<< "${resp}"); then
+              echo "Failed to retrieve OIDC token from GitHub. Response:"
+              echo "${resp}" | jq .
+              exit 1
+          fi
+
+          # echo "::add-mask::${oidc_token}"
+          echo "oidc-token=${oidc_token}" >> "${GITHUB_OUTPUT}"
+
+      - name: Exchange PyPI OIDC token for API token
+        id: retrieve-pypi-token
+        run: |
+          set -euo pipefail
+
+          resp=$(curl -sSf -X POST "https://pypi.org/_/oidc/mint-token" \
+                  -H "Content-Type: application/json" \
+                  --data "{\"token\":\"${{ steps.retrieve-pypi-oidc-token.outputs.oidc-token }}\"}")
+
+          if ! api_token=$(jq -er '.token' <<< "${resp}"); then
+              echo "Failed to exchange OIDC token for a PyPI API token. Response:"
+              echo "${resp}" | jq .
+              exit 1
+          fi
+
+          # echo "::add-mask::${api_token}"
+          echo "api-token=${api_token}" >> "${GITHUB_OUTPUT}"
